# -*- coding: utf-8 -*-
"""datasetMapaBiomas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lSUe2WHB4RvKxC5RyMlf_DM3JEF_rhDh
"""

import pandas as pd
from google.colab import files

import pandas as pd

# Mapeamento de código para sigla de estado
codigo_para_sigla = {
    12: "AC", 27: "AL", 13: "AM", 16: "AP", 29: "BA", 23: "CE", 53: "DF", 32: "ES",
    52: "GO", 21: "MA", 31: "MG", 50: "MS", 51: "MT", 15: "PA", 25: "PB", 26: "PE",
    22: "PI", 41: "PR", 33: "RJ", 24: "RN", 43: "RS", 11: "RO", 14: "RR", 42: "SC",
    28: "SE", 35: "SP", 17: "TO"
}

# Meses com número e nome
meses = [
    (1, "Jan"), (2, "Fev"), (3, "Mar"), (4, "Abr"), (5, "Mai"), (6, "Jun"),
    (7, "Jul"), (8, "Ago"), (9, "Set"), (10, "Out"), (11, "Nov"), (12, "Dez")
]

#lista que vai armazenar os dfs de cada mês e ano.
dfs = []

# Loop pelos anos
for ano in range(2019, 2026):

    if ano == 2025:
        meses_do_ano = meses[:3] #arquivos de 2025 vão até março
    else:
        meses_do_ano = meses

    for mes_num, mes_nome in meses_do_ano:
        nome_arquivo = f"{ano} {mes_nome} Territórios mais afetados.csv"
        df = pd.read_csv(nome_arquivo)#lê o arquivo

        df["_ano"] = ano
        df["_mes"] = mes_num
        df["_estado"] = df["Code"].map(codigo_para_sigla) #converte o código para a sigla do estado com o map().
        df.rename(columns={"Area_ha": "que_area_queimada"}, inplace=True) #renomeia a coluna de área para "que_area_queimada"
        df = df[["_ano", "_mes", "_estado", "que_area_queimada"]] #mantém apenas essas colunas

        dfs.append(df) #adiciona o df atual na lista


df_total = pd.concat(dfs, ignore_index=True) # concatena todos os dfs

print(df_total)

df_total.to_csv("dados_area_queimada_total.csv", index=False)
files.download("dados_area_queimada_total.csv")