# -*- coding: utf-8 -*-
"""cooking_1985_2023_mapBiomas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rW_ZUfDdaF8HSxoAvqBK5tKZs-NA3AU1
"""

import pandas as pd
import os
from google.colab import files

# meses com numero e nome
meses = {
    "Janeiro": 1, "Fevereiro": 2, "Março": 3, "Abril": 4, "Maio": 5, "Junho": 6,
    "Julho": 7, "Agosto": 8, "Setembro": 9, "Outubro": 10, "Novembro": 11, "Dezembro": 12
}

#pasta onde esta os arquivos
pasta_atual = "/content"


dfs = []

# percorre todos os arquivos .csv no diretório atual
for nome_arquivo in os.listdir(pasta_atual):
    if nome_arquivo.endswith(".csv"):
        estado = nome_arquivo.split()[0]  # Pega a sigla do estado do início do nome do arquivo
        caminho_arquivo = os.path.join(pasta_atual, nome_arquivo)

       #Lê o CSV e renomeia a primeira coluna para "Classe", se necessário
        df = pd.read_csv(caminho_arquivo,  na_values="-")

        df_long = df.melt(id_vars=["Classe"], var_name="_ano", value_name="que_area_queimada")
        df_long["_mes"] = df_long["Classe"].map(meses)
        df_long["_mes"] = df_long["_mes"].astype(int)
        df_long["_estado"] = estado

        df_final = df_long[["_ano", "_mes", "_estado", "que_area_queimada"]]
        dfs.append(df_final)

# Junta todos os dataframes
df_total = pd.concat(dfs, ignore_index= True)
print(df_total)

# Salva e exporta
df_total.to_csv("dados_area_queimada_total_certo.csv", index=False)
files.download("dados_area_queimada_total_certo.csv")